[package]
name = "elderheim-target"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Target and executable-format identifiers for Elderheim."

[dependencies]

[lints]
workspace = true
